export interface Contact {
  Id: string;
  IsDeleted?: boolean;
  MasterRecordId?: string | null;
  AccountId?: string | null;
  LastName?: string;
  FirstName?: string;
  Salutation?: string | null;
  Name?: string;
  OtherStreet?: string | null;
  OtherCity?: string | null;
  OtherState?: string | null;
  OtherPostalCode?: string | null;
  OtherCountry?: string | null;
  OtherLatitude?: number | null;
  OtherLongitude?: number | null;
  OtherGeocodeAccuracy?: string | null;
  OtherAddress?: string | null;
  MailingStreet?: string | null;
  MailingCity?: string | null;
  MailingState?: string | null;
  MailingPostalCode?: string | null;
  MailingCountry?: string | null;
  MailingLatitude?: number | null;
  MailingLongitude?: number | null;
  MailingGeocodeAccuracy?: string | null;
  MailingAddress?: string | null;
  Phone?: string | null;
  Fax?: string | null;
  MobilePhone?: string | null;
  HomePhone?: string | null;
  OtherPhone?: string | null;
  AssistantPhone?: string | null;
  ReportsToId?: string | null;
  Email?: string | null;
  Title?: string | null;
  Department?: string | null;
  AssistantName?: string | null;
  LeadSource?: string | null;
  Birthdate?: string | null;
  Description?: string | null;
  OwnerId?: string;
  CreatedDate?: string;
  CreatedById?: string;
  LastModifiedDate?: string;
  LastModifiedById?: string;
  SystemModstamp?: string;
  LastActivityDate?: string | null;
  LastCURequestDate?: string | null;
  LastCUUpdateDate?: string | null;
  LastViewedDate?: string;
  LastReferencedDate?: string;
  EmailBouncedReason?: string | null;
  EmailBouncedDate?: string | null;
  IsEmailBounced?: boolean;
  PhotoUrl?: string;
  Jigsaw?: string | null;
  JigsawContactId?: string | null;
  CleanStatus?: string;
  IndividualId?: string | null;
  Level__c?: string | null;
  Languages__c?: string | null;
  Prequalified__c?: boolean;
  Loan_Amount__c?: number | null;
}
